Repository croct-tech/plug-react, pull requests merged in 2021-06, with the labels that each got.

#10 Fix Plug initialization on server-side
  src/hooks/useCroct.ssr.test.tsx
  src/ssr-polyfills.ssr.test.ts
  src/ssr-polyfills.ts
Labels: bug

#11 Fix promise checking
  src/hooks/useLoader.ts
Labels: bug

#12 Fix previous promise checking
  src/hooks/useLoader.ts
Labels: bug

#14 Add test examples
  .eslintrc.json
  .github/workflows/branch-validations.yaml
  examples/csr-app/package-lock.json
  examples/csr-app/package.json
  examples/csr-app/src/components/HomeBanner/index.test.tsx
  examples/csr-app/src/components/HomeBanner/index.tsx
  examples/csr-app/src/components/PersonaSelector/index.test.tsx
  examples/csr-app/src/components/PersonaSelector/index.tsx
  examples/csr-app/src/setupTests.ts
  examples/next-ssr-app/.babelrc
  examples/next-ssr-app/components/HomeBanner.test.tsx
  examples/next-ssr-app/components/HomeBanner.tsx
  examples/next-ssr-app/components/PersonaSelector.test.tsx
  examples/next-ssr-app/components/PersonaSelector.tsx
  examples/next-ssr-app/jest.config.js
  examples/next-ssr-app/package-lock.json
  examples/next-ssr-app/package.json
  jest.config.js
Labels: documentation

#15 Improve tests and descriptions
  examples/csr-app/src/components/HomeBanner/index.test.tsx
  examples/csr-app/src/components/PersonaSelector/index.test.tsx
  examples/next-ssr-app/components/HomeBanner.test.tsx
  examples/next-ssr-app/components/PersonaSelector.test.tsx
  src/CroctProvider.test.tsx
  src/components/Personalization/index.d.test.tsx
  src/components/Personalization/index.test.tsx
  src/components/Slot/index.d.test.tsx
  src/components/Slot/index.test.tsx
Labels: enhancement

#17 Update dependencies to resolve security risks
  audit-resolve.json
  package-lock.json
  package.json
Labels: maintenance

#16 docs: Fixing errors and patterns
  README.md
Labels: documentation

#18 Bump dependency versions
  audit-resolve.json
  package-lock.json
  package.json
Labels: maintenance
